AWSTemplateFormatVersion: 2010-09-09
Description: Master Panther backend template

Parameters:
  CloudWatchLogRetentionDays:
    Type: Number
    Description: CloudWatch log retention period
    Default: 365
  Debug:
    Type: String
    Description: Toggle debug logging
    Default: false
    AllowedValues:
      - true
      - false
  ExecutionRoleArn:
    Type: String
    Description: Use a single existing execution role for all Lambda functions
    Default: ''
  LayerVersionArns:
    Type: CommaDelimitedList
    Description: List of LayerVersion ARNs to attach to every function
    Default: ''

Resources:
  GatewayLoggingRole:
    Type: AWS::IAM::Role
    Properties:
      Description: API Gateway uses this role to publish logs to CloudWatch
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      Tags:
        - Key: Application
          Value: Panther

  GatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt GatewayLoggingRole.Arn

  QueueEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Encryption key for all panther SQS queues
      EnableKeyRotation: true
      KeyPolicy:
        # Allow account root user to administer key (required)
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
      Tags:
        - Key: Application
          Value: Panther

  QueueEncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/panther-sqs
      TargetKeyId: !Ref QueueEncryptionKey

  ##### Nested Stacks #####
  ComplianceAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        Debug: !Ref Debug
        ExecutionRoleArn: !Ref ExecutionRoleArn
        LayerVersionArns: !Join [ ",", !Ref LayerVersionArns ]
      Tags:
        - Key: Application
          Value: Panther
        - Key: Component
          Value: AnalysisAPI
      TemplateURL: ../out/deployments/compliance/swagger.compliance-api.yml

  AnalysisAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        Debug: !Ref Debug
        ExecutionRoleArn: !Ref ExecutionRoleArn
        LayerVersionArns: !Join [ ",", !Ref LayerVersionArns ]
        ComplianceApiId: !GetAtt ComplianceAPI.Outputs.GatewayId
        S3BucketAccessLogs: !ImportValue Panther-LogBucket
        SQSKeyId: !Ref QueueEncryptionKey
      Tags:
        - Key: Application
          Value: Panther
        - Key: Component
          Value: AnalysisAPI
      TemplateURL: ../out/deployments/shared/swagger.analysis-api.yml

Outputs:
  AnalysisApiEndpoint:
    Description: panther-analysis-api Gateway HTTPS endpoint
    Value: !Sub '${AnalysisAPI.Outputs.GatewayId}.execute-api.${AWS::Region}.amazonaws.com'
  ComplianceApiEndpoint:
    Description: panther-compliance-api Gateway HTTPS endpoint
    Value: !Sub '${ComplianceAPI.Outputs.GatewayId}.execute-api.${AWS::Region}.amazonaws.com'
