AWSTemplateFormatVersion: 2010-09-09
Description: Master Panther backend template

Parameters:
  CloudWatchLogRetentionDays:
    Type: Number
    Description: CloudWatch log retention period
    Default: 365
  Debug:
    Type: String
    Description: Toggle debug logging
    Default: false
    AllowedValues: [true, false]
  LayerVersionArns:
    Type: CommaDelimitedList
    Description: List of LayerVersion ARNs to attach to every function
    Default: ''
  TracingMode:
    Type: String
    Description: Enable XRay tracing on Lambda and API Gateway
    AllowedValues: ['', Active, PassThrough]
    Default: ''

  PythonLayerObjectVersion:
    Type: String
    Description: S3 object version for the python layer zipfile
    Default: ''
  PythonLayerKey:
    Type: String
    Description: S3 key for the Python analysis layer
    Default: layers/python-analysis.zip

Resources:
  GatewayLoggingRole:
    Type: AWS::IAM::Role
    Properties:
      Description: API Gateway uses this role to publish logs to CloudWatch
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      Tags:
        - Key: Application
          Value: Panther

  GatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt GatewayLoggingRole.Arn

  QueueEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Encryption key for all panther SQS queues
      EnableKeyRotation: true
      KeyPolicy:
        # Allow account root user to administer key (required)
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action:
              - kms:GenerateDataKey
              - kms:Decrypt
            Resource: '*'
      Tags:
        - Key: Application
          Value: Panther

  QueueEncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/panther-sqs
      TargetKeyId: !Ref QueueEncryptionKey

  PythonLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.6
        - python3.7
      Content:
        S3Bucket: !Sub panther-source-${AWS::AccountId}-${AWS::Region}
        S3Key: !Ref PythonLayerKey
        S3ObjectVersion: !Ref PythonLayerObjectVersion
      Description: Pip libraries available to the Python analysis/remediation functions
      LayerName: panther-analysis

  ##### Nested Stacks: Core Infra #####
  AnalysisAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        Debug: !Ref Debug
        LayerVersionArns: !Join [ ',', !Ref LayerVersionArns ]
        TracingMode: !Ref TracingMode

        ComplianceApiId: !GetAtt ComplianceAPI.Outputs.GatewayId
        PythonLayerArn: !Ref PythonLayer
        S3BucketAccessLogs: !ImportValue Panther-LogBucket
        SQSKeyId: !Ref QueueEncryptionKey
      Tags:
        - Key: Application
          Value: Panther
      TemplateURL: ../out/deployments/core/swagger.analysis_api.yml

  AlertDelivery:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        Debug: !Ref Debug
        LayerVersionArns: !Join [ ',', !Ref LayerVersionArns ]
        TracingMode: !Ref TracingMode

        AppFqdn: app.runpanther.io  # TODO - this is just a placeholder
        SQSKeyId: !Ref QueueEncryptionKey
      Tags:
        - Key: Application
          Value: Panther
      TemplateURL: core/outputs.yml

  AdminAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        Debug: !Ref Debug
        LayerVersionArns: !Join [ ",", !Ref LayerVersionArns ]
        TracingMode: !Ref TracingMode
      Tags:
        - Key: Application
          Value: Panther
      TemplateURL: core/admin_api.yml

  ##### Nested Stacks: Compliance #####
  ComplianceAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        Debug: !Ref Debug
        LayerVersionArns: !Join [ ',', !Ref LayerVersionArns ]
        TracingMode: !Ref TracingMode
      Tags:
        - Key: Application
          Value: Panther
      TemplateURL: ../out/deployments/compliance/swagger.compliance_api.yml

  ResourcesAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        Debug: !Ref Debug
        LayerVersionArns: !Join [ ',', !Ref LayerVersionArns ]
        TracingMode: !Ref TracingMode

        AnalysisApiId: !GetAtt AnalysisAPI.Outputs.GatewayId
        ComplianceApiId: !GetAtt ComplianceAPI.Outputs.GatewayId
        SQSKeyId: !Ref QueueEncryptionKey
      Tags:
        - Key: Application
          Value: Panther
      TemplateURL: ../out/deployments/compliance/swagger.resources_api.yml

  AwsEventProcessor:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        Debug: !Ref Debug
        LayerVersionArns: !Join [ ',', !Ref LayerVersionArns ]
        TracingMode: !Ref TracingMode

        ResourcesApiId: !GetAtt ResourcesAPI.Outputs.GatewayId
        SQSKeyId: !Ref QueueEncryptionKey
      Tags:
        - Key: Application
          Value: Panther
      TemplateURL: compliance/aws_event_processor.yml

  SnapshotInfra:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        Debug: !Ref Debug
        LayerVersionArns: !Join [ ',', !Ref LayerVersionArns ]
        TracingMode: !Ref TracingMode

        ResourcesApiId: !GetAtt ResourcesAPI.Outputs.GatewayId
        SQSKeyId: !Ref QueueEncryptionKey
      Tags:
        - Key: Application
          Value: Panther
      TemplateURL: compliance/snapshot.yml

  AlertProcessing:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        Debug: !Ref Debug
        LayerVersionArns: !Join [ ',', !Ref LayerVersionArns ]
        TracingMode: !Ref TracingMode

        AnalysisApiId: !GetAtt AnalysisAPI.Outputs.GatewayId
        ComplianceApiId: !GetAtt ComplianceAPI.Outputs.GatewayId
        RemediationApiId: !GetAtt RemediationAPI.Outputs.GatewayId
        SQSKeyId: !Ref QueueEncryptionKey
      Tags:
        - Key: Application
          Value: Panther
      TemplateURL: compliance/alert_processing.yml

  RemediationAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        Debug: !Ref Debug
        LayerVersionArns: !Join [ ',', !Ref LayerVersionArns ]
        TracingMode: !Ref TracingMode

        AnalysisApiId: !GetAtt AnalysisAPI.Outputs.GatewayId
        PythonLayerArn: !Ref PythonLayer
        ResourcesApiId: !GetAtt ResourcesAPI.Outputs.GatewayId
        SQSKeyId: !Ref QueueEncryptionKey
      Tags:
        - Key: Application
          Value: Panther
      TemplateURL: ../out/deployments/compliance/swagger.remediation.yml

  ##### Nested Stacks: Log Analysis #####
  ProcessedDataNotifications:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: panther-processed-data-notifications
      KmsMasterKeyId: !Ref QueueEncryptionKey

  ProcessedDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub panther-processed-data-${AWS::AccountId}-${AWS::Region}
      LoggingConfiguration:
        DestinationBucketName: !ImportValue Panther-LogBucket
        LogFilePrefix: !Sub panther-classified-data-${AWS::AccountId}-${AWS::Region}/
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled

  LogProcessor:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        Debug: !Ref Debug
        LayerVersionArns: !Join [ ',', !Ref LayerVersionArns ]
        TracingMode: !Ref TracingMode

        SnsTopicArn: !Ref ProcessedDataNotifications
        ProcessedDataBucket: !Ref ProcessedDataBucket
        SQSKeyId: !Ref QueueEncryptionKey
      Tags:
        - Key: Application
          Value: Panther
      TemplateURL: log_analysis/log_processor.yml

Outputs:
  AnalysisApiEndpoint:
    Description: panther-analysis-api Gateway HTTPS endpoint
    Value: !Sub '${AnalysisAPI.Outputs.GatewayId}.execute-api.${AWS::Region}.amazonaws.com'
  ComplianceApiEndpoint:
    Description: panther-compliance-api Gateway HTTPS endpoint
    Value: !Sub '${ComplianceAPI.Outputs.GatewayId}.execute-api.${AWS::Region}.amazonaws.com'
  ResourcesApiEndpoint:
    Description: panther-resources-api Gateway HTTPS endpoint
    Value: !Sub '${ResourcesAPI.Outputs.GatewayId}.execute-api.${AWS::Region}.amazonaws.com'
