##### Panther deployment configuration #####

# CloudFormation parameter overrides for the core/buckets.yml prerequisite stack.
BucketsParameterValues:
  # Use an existing S3 bucket for storing access logs. If not specified, one is created for you.
  AccessLogsBucketName: ''


# CloudFormation parameter overrides for the template.yml main application stack.
AppParameterValues:
  # The email and first/last name for the initial Panther admin user.
  #
  # "mage deploy" will prompt for and overwrite these values if the email is left blank.
  #
  # Changing any of these values after the initial deploy will delete the existing user and create
  # a new one in their place.
  UserEmail: '' # REQUIRED
  UserGivenName: ''
  UserFamilyName: ''

  # Retention period for all Panther CloudWatch log groups.
  CloudWatchLogRetentionDays: 365

  # Enable DEBUG logging for all Lambda functions.
  Debug: false

  # Comma-delimited list of LayerVersions to attach to every Lambda function.
  #
  # For example, this could be a serverless monitoring/security service.
  LayerVersionArns: ''

  # Custom layer attached to every Python Lambda function for analysis and remediation.
  #
  # If not specified, a layer is created for you based on the PipLayer setting below.
  PythonLayerVersionArn: ''

  # XRay tracing mode for API Gateway and Lambda: '', 'Active', or 'PassThrough'
  TracingMode: ''


# Create a Python layer with these pip library versions.
#
# This makes it easy to add your own pip libraries for analysis and remediation.
# Natively compiled libraries (e.g. numpy) are not currently supported: build a custom layer instead.
#
# This setting has no effect if PythonLayerVersionArn is set above.
PipLayer:
  - boto3==1.10.46
  - policyuniverse==1.3.2.1
  - requests==2.22.0


# List of policy/rule sets to install when Panther is FIRST deployed.
#
# Entries can be URLs or file:// paths that point to a .zip file.
# If the analysis-api is already deployed and non-empty, this setting is ignored and you can instead
# use the BulkUpload functionality from the web app to upload new or modified rule sets.
InitialAnalysisSets:
  - example.com/default-rules.zip  # TODO - by default, point to a Panther github release artifact
