### Panther deployment configuration ###

# These are passed as CloudFormation parameter overrides for the template.yml stack.
ParameterValues:
  UserEmail: # TODO - REQUIRED
  UserGivenName: ''
  UserFamilyName: ''

  CloudWatchLogRetentionDays: 365
  Debug: false
  LayerVersionArns: ''
  TracingMode: ''
