linters:
  disable-all: true
  enable:
    # enabled by default
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck

    # others to enable
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - funlen
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - lll
    - maligned
    - misspell
    - nakedret
    - scopelint
    - stylecheck
    - unconvert
    - unparam
    - whitespace

  # don't enable:
  # - gochecknoinits
  # - gochecknoglobals
  # - gocognit
  # - godox
  # - interfacer
  # - prealloc
  # - wsl

linters-settings:
  funlen:
    lines: 120
    statements: 60
  lll:
    line-length: 140
  whitespace:
    multi-if: true   # Enforces newlines (or comments) after every multi-line if statement
    multi-func: true # Enforces newlines (or comments) after every multi-line function signature

issues:
  exclude-rules:
    - path: '_test\.go'
      linters:
        - bodyclose
        - dupl
        - funlen
        - unparam
    - path: api/snapshot/aws/
      linters:
        # struct field names are designed for Python access, won't match Go style
        - golint
        - stylecheck
    - path: internal/compliance/aws_event_processor/processor/
      linters:
        # long switch statements for aws event types don't need to be broken up
        - funlen
        - gocyclo
