linters:
  disable-all: true
  enable:
    # enabled by default
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck

    # others to enable
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - funlen
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - lll
    - maligned
    - misspell
    - nakedret
    - scopelint
    - stylecheck
    - unconvert
    - unparam
    - whitespace

  # don't enable:
  # - gochecknoinits
  # - gochecknoglobals
  # - godox
  # - interfacer
  # - prealloc
  # - wsl

linters-settings:
  funlen:
    lines: 120
    statements: 60

  whitespace:
    multi-if: true   # Enforces newlines (or comments) after every multi-line if statement
    multi-func: true # Enforces newlines (or comments) after every multi-line function signature

issues:
  exclude-rules:
    - path: '.*_test.go'
      linters:
        - bodyclose
        - dupl
