version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
    commands:
      - go get github.com/magefile/mage
      - mage -v setup
      - export PATH=/root/.local/bin:$PATH
  build:
    commands:
      - mage test:ci
