version: 0.2

env:
  variables:
    CI: "true"

phases:
  install:
    runtime-versions:
      golang: 1.13
      nodejs: 10
    commands:
      - go get github.com/magefile/mage
      - mage -v setup
      - export PATH=/root/.local/bin:$PATH
      - cd web
      - npm i
      - cd $CODEBUILD_SRC_DIR
  build:
    commands:
      - mage test:ci
      - cd web
      - npm audit
      - npm run lint
