AWSTemplateFormatVersion: 2010-09-09
Description: Prerequisite S3 buckets which must exist before the Panther backend can be deployed

Parameters:
  AccessLogsBucketName:
    Type: String
    Description: Existing bucket for storing S3 access logs (by default, a bucket is created for you)
    Default: ''

Conditions:
  CreateLogBucket: !Equals [!Ref AccessLogsBucketName, '']

Resources:
  # S3 bucket for Panther S3 access logs
  AccessLogsBucket:
    Condition: CreateLogBucket
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub panther-s3-logs-${AWS::AccountId}-${AWS::Region}
      LifecycleConfiguration:
        Rules:
          # Keep access logs for 1 year, permanently delete 30 days after they expire
          - ExpirationInDays: 365
            NoncurrentVersionExpirationInDays: 30
            Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Sub panther-s3-logs-${AWS::AccountId}-${AWS::Region}
        LogFilePrefix: !Sub panther-s3-logs-${AWS::AccountId}-${AWS::Region}/
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Application
          Value: Panther
      VersioningConfiguration:
        Status: Enabled

  # S3 bucket for CloudFormation to upload templates, Lambda source, etc
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub panther-source-${AWS::AccountId}-${AWS::Region}
      LifecycleConfiguration:
        Rules:
          # Once a stack is deployed, its resources in S3 can be safely removed.
          - ExpirationInDays: 90
            Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !If [CreateLogBucket, !Ref AccessLogsBucket, !Ref AccessLogsBucketName]
        LogFilePrefix: !Sub panther-source-${AWS::AccountId}-${AWS::Region}/
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Application
          Value: Panther
      VersioningConfiguration:
        Status: Enabled

Outputs:
  LogBucketName:
    Description: S3 bucket name for Panther S3 access logs
    Value: !If [CreateLogBucket, !Ref AccessLogsBucket, !Ref AccessLogsBucketName]
    Export:
      Name: Panther-LogBucket
  SourceBucketName:
    Description: S3 bucket name for Panther CloudFormation packaging
    Value: !Ref SourceBucket
