// Code generated by go-swagger; DO NOT EDIT.

package models

/**
 * Copyright 2020 Panther Labs Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ComplianceStatus Pass/fail compliance status
// swagger:model complianceStatus
type ComplianceStatus string

const (

	// ComplianceStatusERROR captures enum value "ERROR"
	ComplianceStatusERROR ComplianceStatus = "ERROR"

	// ComplianceStatusFAIL captures enum value "FAIL"
	ComplianceStatusFAIL ComplianceStatus = "FAIL"

	// ComplianceStatusPASS captures enum value "PASS"
	ComplianceStatusPASS ComplianceStatus = "PASS"
)

// for schema
var complianceStatusEnum []interface{}

func init() {
	var res []ComplianceStatus
	if err := json.Unmarshal([]byte(`["ERROR","FAIL","PASS"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		complianceStatusEnum = append(complianceStatusEnum, v)
	}
}

func (m ComplianceStatus) validateComplianceStatusEnum(path, location string, value ComplianceStatus) error {
	if err := validate.Enum(path, location, value, complianceStatusEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this compliance status
func (m ComplianceStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateComplianceStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
