// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Copyright 2020 Panther Labs Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"

	models "github.com/panther-labs/panther/api/gateway/resources/models"
)

// AddResourcesReader is a Reader for the AddResources structure.
type AddResourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddResourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAddResourcesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAddResourcesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAddResourcesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddResourcesCreated creates a AddResourcesCreated with default headers values
func NewAddResourcesCreated() *AddResourcesCreated {
	return &AddResourcesCreated{}
}

/*AddResourcesCreated handles this case with default header values.

OK
*/
type AddResourcesCreated struct {
}

func (o *AddResourcesCreated) Error() string {
	return fmt.Sprintf("[POST /resource][%d] addResourcesCreated ", 201)
}

func (o *AddResourcesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddResourcesBadRequest creates a AddResourcesBadRequest with default headers values
func NewAddResourcesBadRequest() *AddResourcesBadRequest {
	return &AddResourcesBadRequest{}
}

/*AddResourcesBadRequest handles this case with default header values.

Bad request
*/
type AddResourcesBadRequest struct {
	Payload *models.Error
}

func (o *AddResourcesBadRequest) Error() string {
	return fmt.Sprintf("[POST /resource][%d] addResourcesBadRequest  %+v", 400, o.Payload)
}

func (o *AddResourcesBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *AddResourcesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddResourcesInternalServerError creates a AddResourcesInternalServerError with default headers values
func NewAddResourcesInternalServerError() *AddResourcesInternalServerError {
	return &AddResourcesInternalServerError{}
}

/*AddResourcesInternalServerError handles this case with default header values.

Internal server error
*/
type AddResourcesInternalServerError struct {
}

func (o *AddResourcesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /resource][%d] addResourcesInternalServerError ", 500)
}

func (o *AddResourcesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
