// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Copyright 2020 Panther Labs Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"

	models "github.com/panther-labs/panther/api/gateway/resources/models"
)

// DeleteResourcesReader is a Reader for the DeleteResources structure.
type DeleteResourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteResourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteResourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteResourcesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteResourcesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteResourcesOK creates a DeleteResourcesOK with default headers values
func NewDeleteResourcesOK() *DeleteResourcesOK {
	return &DeleteResourcesOK{}
}

/*DeleteResourcesOK handles this case with default header values.

OK
*/
type DeleteResourcesOK struct {
}

func (o *DeleteResourcesOK) Error() string {
	return fmt.Sprintf("[POST /delete][%d] deleteResourcesOK ", 200)
}

func (o *DeleteResourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteResourcesBadRequest creates a DeleteResourcesBadRequest with default headers values
func NewDeleteResourcesBadRequest() *DeleteResourcesBadRequest {
	return &DeleteResourcesBadRequest{}
}

/*DeleteResourcesBadRequest handles this case with default header values.

Bad request
*/
type DeleteResourcesBadRequest struct {
	Payload *models.Error
}

func (o *DeleteResourcesBadRequest) Error() string {
	return fmt.Sprintf("[POST /delete][%d] deleteResourcesBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteResourcesBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteResourcesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteResourcesInternalServerError creates a DeleteResourcesInternalServerError with default headers values
func NewDeleteResourcesInternalServerError() *DeleteResourcesInternalServerError {
	return &DeleteResourcesInternalServerError{}
}

/*DeleteResourcesInternalServerError handles this case with default header values.

Internal server error
*/
type DeleteResourcesInternalServerError struct {
}

func (o *DeleteResourcesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /delete][%d] deleteResourcesInternalServerError ", 500)
}

func (o *DeleteResourcesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
