// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Copyright 2020 Panther Labs Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"

	models "github.com/panther-labs/panther/api/gateway/resources/models"
)

// ListResourcesReader is a Reader for the ListResources structure.
type ListResourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListResourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListResourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListResourcesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListResourcesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListResourcesOK creates a ListResourcesOK with default headers values
func NewListResourcesOK() *ListResourcesOK {
	return &ListResourcesOK{}
}

/*ListResourcesOK handles this case with default header values.

OK
*/
type ListResourcesOK struct {
	Payload *models.ResourceList
}

func (o *ListResourcesOK) Error() string {
	return fmt.Sprintf("[GET /list][%d] listResourcesOK  %+v", 200, o.Payload)
}

func (o *ListResourcesOK) GetPayload() *models.ResourceList {
	return o.Payload
}

func (o *ListResourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListResourcesBadRequest creates a ListResourcesBadRequest with default headers values
func NewListResourcesBadRequest() *ListResourcesBadRequest {
	return &ListResourcesBadRequest{}
}

/*ListResourcesBadRequest handles this case with default header values.

Bad request
*/
type ListResourcesBadRequest struct {
	Payload *models.Error
}

func (o *ListResourcesBadRequest) Error() string {
	return fmt.Sprintf("[GET /list][%d] listResourcesBadRequest  %+v", 400, o.Payload)
}

func (o *ListResourcesBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListResourcesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListResourcesInternalServerError creates a ListResourcesInternalServerError with default headers values
func NewListResourcesInternalServerError() *ListResourcesInternalServerError {
	return &ListResourcesInternalServerError{}
}

/*ListResourcesInternalServerError handles this case with default header values.

Internal server error
*/
type ListResourcesInternalServerError struct {
}

func (o *ListResourcesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /list][%d] listResourcesInternalServerError ", 500)
}

func (o *ListResourcesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
