// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Copyright 2020 Panther Labs Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"

	models "github.com/panther-labs/panther/api/gateway/compliance/models"
)

// DeleteStatusReader is a Reader for the DeleteStatus structure.
type DeleteStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteStatusBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteStatusInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteStatusOK creates a DeleteStatusOK with default headers values
func NewDeleteStatusOK() *DeleteStatusOK {
	return &DeleteStatusOK{}
}

/*DeleteStatusOK handles this case with default header values.

OK
*/
type DeleteStatusOK struct {
}

func (o *DeleteStatusOK) Error() string {
	return fmt.Sprintf("[POST /delete][%d] deleteStatusOK ", 200)
}

func (o *DeleteStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteStatusBadRequest creates a DeleteStatusBadRequest with default headers values
func NewDeleteStatusBadRequest() *DeleteStatusBadRequest {
	return &DeleteStatusBadRequest{}
}

/*DeleteStatusBadRequest handles this case with default header values.

Bad request
*/
type DeleteStatusBadRequest struct {
	Payload *models.Error
}

func (o *DeleteStatusBadRequest) Error() string {
	return fmt.Sprintf("[POST /delete][%d] deleteStatusBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteStatusBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteStatusBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteStatusInternalServerError creates a DeleteStatusInternalServerError with default headers values
func NewDeleteStatusInternalServerError() *DeleteStatusInternalServerError {
	return &DeleteStatusInternalServerError{}
}

/*DeleteStatusInternalServerError handles this case with default header values.

Internal server error
*/
type DeleteStatusInternalServerError struct {
}

func (o *DeleteStatusInternalServerError) Error() string {
	return fmt.Sprintf("[POST /delete][%d] deleteStatusInternalServerError ", 500)
}

func (o *DeleteStatusInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
