// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Copyright 2020 Panther Labs Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"

	models "github.com/panther-labs/panther/api/gateway/compliance/models"
)

// DescribePolicyReader is a Reader for the DescribePolicy structure.
type DescribePolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribePolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDescribePolicyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDescribePolicyBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDescribePolicyInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDescribePolicyOK creates a DescribePolicyOK with default headers values
func NewDescribePolicyOK() *DescribePolicyOK {
	return &DescribePolicyOK{}
}

/*DescribePolicyOK handles this case with default header values.

OK
*/
type DescribePolicyOK struct {
	Payload *models.PolicyResourceDetail
}

func (o *DescribePolicyOK) Error() string {
	return fmt.Sprintf("[GET /describe-policy][%d] describePolicyOK  %+v", 200, o.Payload)
}

func (o *DescribePolicyOK) GetPayload() *models.PolicyResourceDetail {
	return o.Payload
}

func (o *DescribePolicyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PolicyResourceDetail)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribePolicyBadRequest creates a DescribePolicyBadRequest with default headers values
func NewDescribePolicyBadRequest() *DescribePolicyBadRequest {
	return &DescribePolicyBadRequest{}
}

/*DescribePolicyBadRequest handles this case with default header values.

Bad request
*/
type DescribePolicyBadRequest struct {
	Payload *models.Error
}

func (o *DescribePolicyBadRequest) Error() string {
	return fmt.Sprintf("[GET /describe-policy][%d] describePolicyBadRequest  %+v", 400, o.Payload)
}

func (o *DescribePolicyBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DescribePolicyBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribePolicyInternalServerError creates a DescribePolicyInternalServerError with default headers values
func NewDescribePolicyInternalServerError() *DescribePolicyInternalServerError {
	return &DescribePolicyInternalServerError{}
}

/*DescribePolicyInternalServerError handles this case with default header values.

Internal server error
*/
type DescribePolicyInternalServerError struct {
}

func (o *DescribePolicyInternalServerError) Error() string {
	return fmt.Sprintf("[GET /describe-policy][%d] describePolicyInternalServerError ", 500)
}

func (o *DescribePolicyInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
