// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Copyright 2020 Panther Labs Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"

	models "github.com/panther-labs/panther/api/gateway/compliance/models"
)

// DescribeResourceReader is a Reader for the DescribeResource structure.
type DescribeResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDescribeResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDescribeResourceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDescribeResourceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDescribeResourceOK creates a DescribeResourceOK with default headers values
func NewDescribeResourceOK() *DescribeResourceOK {
	return &DescribeResourceOK{}
}

/*DescribeResourceOK handles this case with default header values.

OK
*/
type DescribeResourceOK struct {
	Payload *models.PolicyResourceDetail
}

func (o *DescribeResourceOK) Error() string {
	return fmt.Sprintf("[GET /describe-resource][%d] describeResourceOK  %+v", 200, o.Payload)
}

func (o *DescribeResourceOK) GetPayload() *models.PolicyResourceDetail {
	return o.Payload
}

func (o *DescribeResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PolicyResourceDetail)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribeResourceBadRequest creates a DescribeResourceBadRequest with default headers values
func NewDescribeResourceBadRequest() *DescribeResourceBadRequest {
	return &DescribeResourceBadRequest{}
}

/*DescribeResourceBadRequest handles this case with default header values.

Bad request
*/
type DescribeResourceBadRequest struct {
	Payload *models.Error
}

func (o *DescribeResourceBadRequest) Error() string {
	return fmt.Sprintf("[GET /describe-resource][%d] describeResourceBadRequest  %+v", 400, o.Payload)
}

func (o *DescribeResourceBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DescribeResourceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribeResourceInternalServerError creates a DescribeResourceInternalServerError with default headers values
func NewDescribeResourceInternalServerError() *DescribeResourceInternalServerError {
	return &DescribeResourceInternalServerError{}
}

/*DescribeResourceInternalServerError handles this case with default header values.

Internal server error
*/
type DescribeResourceInternalServerError struct {
}

func (o *DescribeResourceInternalServerError) Error() string {
	return fmt.Sprintf("[GET /describe-resource][%d] describeResourceInternalServerError ", 500)
}

func (o *DescribeResourceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
