// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Copyright 2020 Panther Labs Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"

	models "github.com/panther-labs/panther/api/gateway/compliance/models"
)

// DescribeOrgReader is a Reader for the DescribeOrg structure.
type DescribeOrgReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeOrgReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDescribeOrgOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDescribeOrgBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDescribeOrgInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDescribeOrgOK creates a DescribeOrgOK with default headers values
func NewDescribeOrgOK() *DescribeOrgOK {
	return &DescribeOrgOK{}
}

/*DescribeOrgOK handles this case with default header values.

OK
*/
type DescribeOrgOK struct {
	Payload *models.EntireOrg
}

func (o *DescribeOrgOK) Error() string {
	return fmt.Sprintf("[GET /describe-org][%d] describeOrgOK  %+v", 200, o.Payload)
}

func (o *DescribeOrgOK) GetPayload() *models.EntireOrg {
	return o.Payload
}

func (o *DescribeOrgOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EntireOrg)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribeOrgBadRequest creates a DescribeOrgBadRequest with default headers values
func NewDescribeOrgBadRequest() *DescribeOrgBadRequest {
	return &DescribeOrgBadRequest{}
}

/*DescribeOrgBadRequest handles this case with default header values.

Bad request
*/
type DescribeOrgBadRequest struct {
	Payload *models.Error
}

func (o *DescribeOrgBadRequest) Error() string {
	return fmt.Sprintf("[GET /describe-org][%d] describeOrgBadRequest  %+v", 400, o.Payload)
}

func (o *DescribeOrgBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DescribeOrgBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribeOrgInternalServerError creates a DescribeOrgInternalServerError with default headers values
func NewDescribeOrgInternalServerError() *DescribeOrgInternalServerError {
	return &DescribeOrgInternalServerError{}
}

/*DescribeOrgInternalServerError handles this case with default header values.

Internal server error
*/
type DescribeOrgInternalServerError struct {
}

func (o *DescribeOrgInternalServerError) Error() string {
	return fmt.Sprintf("[GET /describe-org][%d] describeOrgInternalServerError ", 500)
}

func (o *DescribeOrgInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
