// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Copyright 2020 Panther Labs Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"

	models "github.com/panther-labs/panther/api/gateway/compliance/models"
)

// NewSetStatusParams creates a new SetStatusParams object
// with the default values initialized.
func NewSetStatusParams() *SetStatusParams {
	var ()
	return &SetStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetStatusParamsWithTimeout creates a new SetStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetStatusParamsWithTimeout(timeout time.Duration) *SetStatusParams {
	var ()
	return &SetStatusParams{

		timeout: timeout,
	}
}

// NewSetStatusParamsWithContext creates a new SetStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetStatusParamsWithContext(ctx context.Context) *SetStatusParams {
	var ()
	return &SetStatusParams{

		Context: ctx,
	}
}

// NewSetStatusParamsWithHTTPClient creates a new SetStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetStatusParamsWithHTTPClient(client *http.Client) *SetStatusParams {
	var ()
	return &SetStatusParams{
		HTTPClient: client,
	}
}

/*SetStatusParams contains all the parameters to send to the API endpoint
for the set status operation typically these are written to a http.Request
*/
type SetStatusParams struct {

	/*Body*/
	Body *models.SetStatusBatch

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set status params
func (o *SetStatusParams) WithTimeout(timeout time.Duration) *SetStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set status params
func (o *SetStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set status params
func (o *SetStatusParams) WithContext(ctx context.Context) *SetStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set status params
func (o *SetStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set status params
func (o *SetStatusParams) WithHTTPClient(client *http.Client) *SetStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set status params
func (o *SetStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the set status params
func (o *SetStatusParams) WithBody(body *models.SetStatusBatch) *SetStatusParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the set status params
func (o *SetStatusParams) SetBody(body *models.SetStatusBatch) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SetStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
