// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Copyright 2020 Panther Labs Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"

	models "github.com/panther-labs/panther/api/gateway/compliance/models"
)

// SetStatusReader is a Reader for the SetStatus structure.
type SetStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewSetStatusCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSetStatusBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSetStatusInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetStatusCreated creates a SetStatusCreated with default headers values
func NewSetStatusCreated() *SetStatusCreated {
	return &SetStatusCreated{}
}

/*SetStatusCreated handles this case with default header values.

OK
*/
type SetStatusCreated struct {
}

func (o *SetStatusCreated) Error() string {
	return fmt.Sprintf("[POST /status][%d] setStatusCreated ", 201)
}

func (o *SetStatusCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetStatusBadRequest creates a SetStatusBadRequest with default headers values
func NewSetStatusBadRequest() *SetStatusBadRequest {
	return &SetStatusBadRequest{}
}

/*SetStatusBadRequest handles this case with default header values.

Bad request
*/
type SetStatusBadRequest struct {
	Payload *models.Error
}

func (o *SetStatusBadRequest) Error() string {
	return fmt.Sprintf("[POST /status][%d] setStatusBadRequest  %+v", 400, o.Payload)
}

func (o *SetStatusBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *SetStatusBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetStatusInternalServerError creates a SetStatusInternalServerError with default headers values
func NewSetStatusInternalServerError() *SetStatusInternalServerError {
	return &SetStatusInternalServerError{}
}

/*SetStatusInternalServerError handles this case with default header values.

Internal server error
*/
type SetStatusInternalServerError struct {
}

func (o *SetStatusInternalServerError) Error() string {
	return fmt.Sprintf("[POST /status][%d] setStatusInternalServerError ", 500)
}

func (o *SetStatusInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
