// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Copyright 2020 Panther Labs Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"

	models "github.com/panther-labs/panther/api/gateway/compliance/models"
)

// UpdateMetadataReader is a Reader for the UpdateMetadata structure.
type UpdateMetadataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateMetadataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateMetadataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateMetadataBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateMetadataInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateMetadataOK creates a UpdateMetadataOK with default headers values
func NewUpdateMetadataOK() *UpdateMetadataOK {
	return &UpdateMetadataOK{}
}

/*UpdateMetadataOK handles this case with default header values.

OK
*/
type UpdateMetadataOK struct {
}

func (o *UpdateMetadataOK) Error() string {
	return fmt.Sprintf("[POST /update][%d] updateMetadataOK ", 200)
}

func (o *UpdateMetadataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateMetadataBadRequest creates a UpdateMetadataBadRequest with default headers values
func NewUpdateMetadataBadRequest() *UpdateMetadataBadRequest {
	return &UpdateMetadataBadRequest{}
}

/*UpdateMetadataBadRequest handles this case with default header values.

Bad request
*/
type UpdateMetadataBadRequest struct {
	Payload *models.Error
}

func (o *UpdateMetadataBadRequest) Error() string {
	return fmt.Sprintf("[POST /update][%d] updateMetadataBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateMetadataBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateMetadataBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateMetadataInternalServerError creates a UpdateMetadataInternalServerError with default headers values
func NewUpdateMetadataInternalServerError() *UpdateMetadataInternalServerError {
	return &UpdateMetadataInternalServerError{}
}

/*UpdateMetadataInternalServerError handles this case with default header values.

Internal server error
*/
type UpdateMetadataInternalServerError struct {
}

func (o *UpdateMetadataInternalServerError) Error() string {
	return fmt.Sprintf("[POST /update][%d] updateMetadataInternalServerError ", 500)
}

func (o *UpdateMetadataInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
