AWSTemplateFormatVersion: 2010-09-09
Description: >
  Panther IAM Role for creating and managing StackSets. The purpose of this role is to assume
  the execution IAM roles in each target account for configuring various Panther infrastructure.

Metadata:
  Version: v0.1.0

Resources:
  CloudFormationStackSetAdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PantherCloudFormationStackSetAdminRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        -
          PolicyName: AssumeRolesInTargetAccounts
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action: sts:AssumeRole
                Resource: arn:aws:iam::*:role/PantherCloudFormationStackSetExecutionRole

Outputs:
  CloudFormationStackSetAdminRoleArn:
    Description: The Arn of the CloudFormation StackSet IAM Role for sending data to Panther.
    Value: !GetAtt CloudFormationStackSetAdminRole.Arn
