// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Copyright 2020 Panther Labs Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"

	models "github.com/panther-labs/panther/api/gateway/remediation/models"
)

// RemediateResourceAsyncReader is a Reader for the RemediateResourceAsync structure.
type RemediateResourceAsyncReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemediateResourceAsyncReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRemediateResourceAsyncOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRemediateResourceAsyncBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRemediateResourceAsyncInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRemediateResourceAsyncOK creates a RemediateResourceAsyncOK with default headers values
func NewRemediateResourceAsyncOK() *RemediateResourceAsyncOK {
	return &RemediateResourceAsyncOK{}
}

/*RemediateResourceAsyncOK handles this case with default header values.

OK
*/
type RemediateResourceAsyncOK struct {
}

func (o *RemediateResourceAsyncOK) Error() string {
	return fmt.Sprintf("[POST /remediateasync][%d] remediateResourceAsyncOK ", 200)
}

func (o *RemediateResourceAsyncOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRemediateResourceAsyncBadRequest creates a RemediateResourceAsyncBadRequest with default headers values
func NewRemediateResourceAsyncBadRequest() *RemediateResourceAsyncBadRequest {
	return &RemediateResourceAsyncBadRequest{}
}

/*RemediateResourceAsyncBadRequest handles this case with default header values.

Bad request
*/
type RemediateResourceAsyncBadRequest struct {
	Payload *models.Error
}

func (o *RemediateResourceAsyncBadRequest) Error() string {
	return fmt.Sprintf("[POST /remediateasync][%d] remediateResourceAsyncBadRequest  %+v", 400, o.Payload)
}

func (o *RemediateResourceAsyncBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *RemediateResourceAsyncBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemediateResourceAsyncInternalServerError creates a RemediateResourceAsyncInternalServerError with default headers values
func NewRemediateResourceAsyncInternalServerError() *RemediateResourceAsyncInternalServerError {
	return &RemediateResourceAsyncInternalServerError{}
}

/*RemediateResourceAsyncInternalServerError handles this case with default header values.

Internal server error
*/
type RemediateResourceAsyncInternalServerError struct {
}

func (o *RemediateResourceAsyncInternalServerError) Error() string {
	return fmt.Sprintf("[POST /remediateasync][%d] remediateResourceAsyncInternalServerError ", 500)
}

func (o *RemediateResourceAsyncInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
