// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Copyright 2020 Panther Labs Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"

	models "github.com/panther-labs/panther/api/gateway/remediation/models"
)

// NewRemediateResourceAsyncParams creates a new RemediateResourceAsyncParams object
// with the default values initialized.
func NewRemediateResourceAsyncParams() *RemediateResourceAsyncParams {
	var ()
	return &RemediateResourceAsyncParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRemediateResourceAsyncParamsWithTimeout creates a new RemediateResourceAsyncParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRemediateResourceAsyncParamsWithTimeout(timeout time.Duration) *RemediateResourceAsyncParams {
	var ()
	return &RemediateResourceAsyncParams{

		timeout: timeout,
	}
}

// NewRemediateResourceAsyncParamsWithContext creates a new RemediateResourceAsyncParams object
// with the default values initialized, and the ability to set a context for a request
func NewRemediateResourceAsyncParamsWithContext(ctx context.Context) *RemediateResourceAsyncParams {
	var ()
	return &RemediateResourceAsyncParams{

		Context: ctx,
	}
}

// NewRemediateResourceAsyncParamsWithHTTPClient creates a new RemediateResourceAsyncParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRemediateResourceAsyncParamsWithHTTPClient(client *http.Client) *RemediateResourceAsyncParams {
	var ()
	return &RemediateResourceAsyncParams{
		HTTPClient: client,
	}
}

/*RemediateResourceAsyncParams contains all the parameters to send to the API endpoint
for the remediate resource async operation typically these are written to a http.Request
*/
type RemediateResourceAsyncParams struct {

	/*Body*/
	Body *models.RemediateResource

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the remediate resource async params
func (o *RemediateResourceAsyncParams) WithTimeout(timeout time.Duration) *RemediateResourceAsyncParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remediate resource async params
func (o *RemediateResourceAsyncParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remediate resource async params
func (o *RemediateResourceAsyncParams) WithContext(ctx context.Context) *RemediateResourceAsyncParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remediate resource async params
func (o *RemediateResourceAsyncParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remediate resource async params
func (o *RemediateResourceAsyncParams) WithHTTPClient(client *http.Client) *RemediateResourceAsyncParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remediate resource async params
func (o *RemediateResourceAsyncParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the remediate resource async params
func (o *RemediateResourceAsyncParams) WithBody(body *models.RemediateResource) *RemediateResourceAsyncParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the remediate resource async params
func (o *RemediateResourceAsyncParams) SetBody(body *models.RemediateResource) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RemediateResourceAsyncParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
