// Code generated by go-swagger; DO NOT EDIT.

package models

/**
 * Copyright 2020 Panther Labs Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrgSummary org summary
// swagger:model OrgSummary
type OrgSummary struct {

	// applied policies
	// Required: true
	AppliedPolicies *StatusCountBySeverity `json:"appliedPolicies"`

	// scanned resources
	// Required: true
	ScannedResources *ScannedResources `json:"scannedResources"`

	// top failing policies
	// Required: true
	TopFailingPolicies []*PolicySummary `json:"topFailingPolicies"`

	// top failing resources
	// Required: true
	TopFailingResources []*ResourceSummary `json:"topFailingResources"`
}

// Validate validates this org summary
func (m *OrgSummary) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAppliedPolicies(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScannedResources(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTopFailingPolicies(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTopFailingResources(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrgSummary) validateAppliedPolicies(formats strfmt.Registry) error {

	if err := validate.Required("appliedPolicies", "body", m.AppliedPolicies); err != nil {
		return err
	}

	if m.AppliedPolicies != nil {
		if err := m.AppliedPolicies.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("appliedPolicies")
			}
			return err
		}
	}

	return nil
}

func (m *OrgSummary) validateScannedResources(formats strfmt.Registry) error {

	if err := validate.Required("scannedResources", "body", m.ScannedResources); err != nil {
		return err
	}

	if m.ScannedResources != nil {
		if err := m.ScannedResources.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("scannedResources")
			}
			return err
		}
	}

	return nil
}

func (m *OrgSummary) validateTopFailingPolicies(formats strfmt.Registry) error {

	if err := validate.Required("topFailingPolicies", "body", m.TopFailingPolicies); err != nil {
		return err
	}

	for i := 0; i < len(m.TopFailingPolicies); i++ {
		if swag.IsZero(m.TopFailingPolicies[i]) { // not required
			continue
		}

		if m.TopFailingPolicies[i] != nil {
			if err := m.TopFailingPolicies[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("topFailingPolicies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *OrgSummary) validateTopFailingResources(formats strfmt.Registry) error {

	if err := validate.Required("topFailingResources", "body", m.TopFailingResources); err != nil {
		return err
	}

	for i := 0; i < len(m.TopFailingResources); i++ {
		if swag.IsZero(m.TopFailingResources[i]) { // not required
			continue
		}

		if m.TopFailingResources[i] != nil {
			if err := m.TopFailingResources[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("topFailingResources" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrgSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrgSummary) UnmarshalBinary(b []byte) error {
	var res OrgSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
