// Code generated by go-swagger; DO NOT EDIT.

package models

/**
 * Copyright 2020 Panther Labs Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// PolicySeverity Policy severity
// swagger:model policySeverity
type PolicySeverity string

const (

	// PolicySeverityINFO captures enum value "INFO"
	PolicySeverityINFO PolicySeverity = "INFO"

	// PolicySeverityLOW captures enum value "LOW"
	PolicySeverityLOW PolicySeverity = "LOW"

	// PolicySeverityMEDIUM captures enum value "MEDIUM"
	PolicySeverityMEDIUM PolicySeverity = "MEDIUM"

	// PolicySeverityHIGH captures enum value "HIGH"
	PolicySeverityHIGH PolicySeverity = "HIGH"

	// PolicySeverityCRITICAL captures enum value "CRITICAL"
	PolicySeverityCRITICAL PolicySeverity = "CRITICAL"
)

// for schema
var policySeverityEnum []interface{}

func init() {
	var res []PolicySeverity
	if err := json.Unmarshal([]byte(`["INFO","LOW","MEDIUM","HIGH","CRITICAL"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		policySeverityEnum = append(policySeverityEnum, v)
	}
}

func (m PolicySeverity) validatePolicySeverityEnum(path, location string, value PolicySeverity) error {
	if err := validate.Enum(path, location, value, policySeverityEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this policy severity
func (m PolicySeverity) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validatePolicySeverityEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
