# Copyright 2020 Panther Labs Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Compliance alert SQS queue and processing functions

Parameters:
  CloudWatchLogRetentionDays:
    Type: Number
    Description: CloudWatch log retention period
    Default: 365
  Debug:
    Type: String
    Description: Toggle debug logging
    Default: false
    AllowedValues: [true, false]
  LayerVersionArns:
    Type: CommaDelimitedList
    Description: List of base LayerVersion ARNs to attach to every Lambda function
    Default: ''
  TracingMode:
    Type: String
    Description: Enable XRay tracing on Lambda and API Gateway
    AllowedValues: ['', Active, PassThrough]
    Default: ''

  ForwarderMemorySizeMB:
    Type: Number
    Description: Memory (MB) available for the alert-forwarder Lambda function
    Default: 128
    MinValue: 128
    MaxValue: 3008
  ForwarderTimeoutSec:
    Type: Number
    Description: Timeout (seconds) for the alert-forwarder Lambda function
    Default: 60
    MinValue: 5
    MaxValue: 900
  ProcessorMemorySizeMB:
    Type: Number
    Description: Memory (MB) available for the alert-processor Lambda function
    Default: 128
    MinValue: 128
    MaxValue: 3008
  ProcessorTimeoutSec:
    Type: Number
    Description: Timeout (seconds) for the alert-processor Lambda function
    Default: 60
    MinValue: 5
    MaxValue: 900

  AnalysisApiId:
    Type: String
    Description: API Gateway for analysis-api
  ComplianceApiId:
    Type: String
    Description: API Gateway for compliance-api
  RemediationApiId:
    Type: String
    Description: API Gateway for remediation-api
  SQSKeyId:
    Type: String
    Description: KMS key ID for SQS encryption

Conditions:
  AttachLayers: !Not [!Equals [!Join ['', !Ref LayerVersionArns], '']]
  TracingEnabled: !Not [!Equals ['', !Ref TracingMode]]

Resources:
  ##### Alert Processor #####
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: panther-alert-processor-queue
      MessageRetentionPeriod: 1209600 # Max duration - 14 days
      KmsMasterKeyId: !Ref SQSKeyId
      Tags:
        - Key: Application
          Value: Panther
      VisibilityTimeout: !Ref ProcessorTimeoutSec
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt [DeadLetterQueue, Arn]
        maxReceiveCount: 10

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: panther-alert-processor-dlq
      MessageRetentionPeriod: 1209600 # Max duration - 14 days
      Tags:
        - Key: Application
          Value: Panther
      VisibilityTimeout: 60

  AlertProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/panther-alert-processor
      RetentionInDays: !Ref CloudWatchLogRetentionDays

  AlertProcessor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../out/bin/internal/compliance/alert_processor/main
      Description: Processes the events generated from the compliance engine
      Environment:
        Variables:
          DEBUG: !Ref Debug
          REMEDIATION_SERVICE_HOST: !Sub '${RemediationApiId}.execute-api.${AWS::Region}.amazonaws.com'
          REMEDIATION_SERVICE_PATH: v1
          COMPLIANCE_SERVICE_HOST: !Sub '${ComplianceApiId}.execute-api.${AWS::Region}.amazonaws.com'
          COMPLIANCE_SERVICE_PATH: v1
          POLICY_SERVICE_HOST: !Sub '${AnalysisApiId}.execute-api.${AWS::Region}.amazonaws.com'
          POLICY_SERVICE_PATH: v1
          TABLE_NAME: !Ref Table
      Events:
        Queue:
          Type: SQS
          Properties:
            Queue: !GetAtt Queue.Arn
            BatchSize: 1
      FunctionName: panther-alert-processor
      Handler: main
      Layers: !If [AttachLayers, !Ref LayerVersionArns, !Ref 'AWS::NoValue']
      MemorySize: !Ref ProcessorMemorySizeMB
      Runtime: go1.x
      Tags:
        Application: Panther
      Timeout: !Ref ProcessorTimeoutSec
      Policies:
        - !If [TracingEnabled, 'arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess', !Ref 'AWS::NoValue']
        -
          Id: ReadFromSQS
          Version: 2012-10-17
          Statement:
            -
              Effect: Allow
              Action:
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
                - sqs:ReceiveMessage
              Resource: !GetAtt Queue.Arn
            -
              Effect: Allow
              Action: kms:Decrypt
              Resource: !Sub arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${SQSKeyId}
        -
          Id: UpdateTable
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: dynamodb:UpdateItem
              Resource: !GetAtt Table.Arn
        -
          Id: InvokeGatewayApi
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: execute-api:Invoke
              Resource:
                - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RemediationApiId}/v1/POST/remediateasync
                - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ComplianceApiId}/v1/GET/status
                - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AnalysisApiId}/v1/GET/policy

  ##### Alert Forwarder #####
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: panther-alert-forwarder
      AttributeDefinitions:
        - AttributeName: policyId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: policyId
          KeyType: HASH
      PointInTimeRecoverySpecification:  # Create periodic table backups
        PointInTimeRecoveryEnabled: True
      SSESpecification:  # Enable server-side encryption
        SSEEnabled: True
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      Tags:
        - Key: Application
          Value: Panther

  AlertForwarderLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/panther-alert-forwarder
      RetentionInDays: !Ref CloudWatchLogRetentionDays

  AlertForwarder:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../out/bin/internal/compliance/alert_forwarder/main
      Description: Forwards the alerts to the alert delivery mechanism
      Environment:
        Variables:
          ALERTING_QUEUE_URL: !Sub https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/panther-alert-processor-queue
          DEBUG: !Ref Debug
      Events:
        DynamoDBEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt Table.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 1
      FunctionName: panther-alert-forwarder
      Handler: main
      MemorySize: !Ref ForwarderMemorySizeMB
      Runtime: go1.x
      Layers: !If [AttachLayers, !Ref LayerVersionArns, !Ref 'AWS::NoValue']
      Tags:
        Application: Panther
      Timeout: !Ref ForwarderTimeoutSec
      Policies:
        - !If [TracingEnabled, 'arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess', !Ref 'AWS::NoValue']
        -
          Id: ReadTableStreams
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeStream
                - dynamodb:GetRecords
                - dynamodb:GetShardIterator
                - dynamodb:ListStreams
              Resource: !Sub ${Table.Arn}/stream/*
        -
          Id: PublishToAlertQueue
          Version: 2012-10-17
          Statement:
            -
              Effect: Allow
              Action:
                - sqs:SendMessage
                - sqs:SendMessageBatch
              Resource: !Sub arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:panther-alerts
            -
              Effect: Allow
              Action:
                - kms:Decrypt
                - kms:GenerateDataKey
              Resource: !Sub arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${SQSKeyId}
