swagger: '2.0'
info:
  version: '1.0.0'
  title: panther-remediation-api
  description: API to invoke remediations
  contact:
    name: Panther Labs
    url: https://runpanther.io/about
    email: support@runpanther.io

schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

# The name of the CloudFormation resource for the Lambda handler function
x-panther-lambda-cfn-resource: ApiFunction

paths:
  /:
    get:
      operationId: ListRemediations
      summary: Retrieve available remediations
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Remediations'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal server error

  /remediate:
    post:
      operationId: RemediateResource
      summary: Synchronously remediate resource for an account.
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/RemediateResource'
      responses:
        200:
          description: OK
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal server error

  /remediateasync:
    post:
      operationId: RemediateResourceAsync
      summary: Asynchronously remediate resource for an account.
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/RemediateResource'
      responses:
        200:
          description: OK
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal server error

definitions:
  RemediateResource:
    type: object
    properties:
      policyId:
        $ref: '#/definitions/PolicyId'
      resourceId:
        $ref: '#/definitions/ResourceId'
    required:
      - policyId
      - resourceId

  Remediations:
    type: object
    additionalProperties:
      type: object

  ##### object properties #####
  PolicyId:
    description: A unique policy ID
    type: string
    minLength: 1
    maxLength: 200

  ResourceId:
    description: Unique resource identifier
    type: string
    minLength: 1
    maxLength: 5000

  Error:
    type: object
    properties:
      message:
        description: Error message
        type: string
    required:
      - message
