// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Copyright 2020 Panther Labs Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"

	models "github.com/panther-labs/panther/api/gateway/analysis/models"
)

// BulkUploadReader is a Reader for the BulkUpload structure.
type BulkUploadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BulkUploadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBulkUploadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewBulkUploadBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewBulkUploadInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewBulkUploadOK creates a BulkUploadOK with default headers values
func NewBulkUploadOK() *BulkUploadOK {
	return &BulkUploadOK{}
}

/*BulkUploadOK handles this case with default header values.

OK
*/
type BulkUploadOK struct {
	Payload *models.BulkUploadResult
}

func (o *BulkUploadOK) Error() string {
	return fmt.Sprintf("[POST /upload][%d] bulkUploadOK  %+v", 200, o.Payload)
}

func (o *BulkUploadOK) GetPayload() *models.BulkUploadResult {
	return o.Payload
}

func (o *BulkUploadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BulkUploadResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBulkUploadBadRequest creates a BulkUploadBadRequest with default headers values
func NewBulkUploadBadRequest() *BulkUploadBadRequest {
	return &BulkUploadBadRequest{}
}

/*BulkUploadBadRequest handles this case with default header values.

Bad request
*/
type BulkUploadBadRequest struct {
	Payload *models.Error
}

func (o *BulkUploadBadRequest) Error() string {
	return fmt.Sprintf("[POST /upload][%d] bulkUploadBadRequest  %+v", 400, o.Payload)
}

func (o *BulkUploadBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *BulkUploadBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBulkUploadInternalServerError creates a BulkUploadInternalServerError with default headers values
func NewBulkUploadInternalServerError() *BulkUploadInternalServerError {
	return &BulkUploadInternalServerError{}
}

/*BulkUploadInternalServerError handles this case with default header values.

Internal server error
*/
type BulkUploadInternalServerError struct {
}

func (o *BulkUploadInternalServerError) Error() string {
	return fmt.Sprintf("[POST /upload][%d] bulkUploadInternalServerError ", 500)
}

func (o *BulkUploadInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
