// Code generated by go-swagger; DO NOT EDIT.

package operations

/**
 * Copyright 2020 Panther Labs Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"

	models "github.com/panther-labs/panther/api/gateway/analysis/models"
)

// GetEnabledPoliciesReader is a Reader for the GetEnabledPolicies structure.
type GetEnabledPoliciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEnabledPoliciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetEnabledPoliciesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetEnabledPoliciesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetEnabledPoliciesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetEnabledPoliciesOK creates a GetEnabledPoliciesOK with default headers values
func NewGetEnabledPoliciesOK() *GetEnabledPoliciesOK {
	return &GetEnabledPoliciesOK{}
}

/*GetEnabledPoliciesOK handles this case with default header values.

OK
*/
type GetEnabledPoliciesOK struct {
	Payload *models.EnabledPolicies
}

func (o *GetEnabledPoliciesOK) Error() string {
	return fmt.Sprintf("[GET /enabled][%d] getEnabledPoliciesOK  %+v", 200, o.Payload)
}

func (o *GetEnabledPoliciesOK) GetPayload() *models.EnabledPolicies {
	return o.Payload
}

func (o *GetEnabledPoliciesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EnabledPolicies)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEnabledPoliciesBadRequest creates a GetEnabledPoliciesBadRequest with default headers values
func NewGetEnabledPoliciesBadRequest() *GetEnabledPoliciesBadRequest {
	return &GetEnabledPoliciesBadRequest{}
}

/*GetEnabledPoliciesBadRequest handles this case with default header values.

Bad request
*/
type GetEnabledPoliciesBadRequest struct {
	Payload *models.Error
}

func (o *GetEnabledPoliciesBadRequest) Error() string {
	return fmt.Sprintf("[GET /enabled][%d] getEnabledPoliciesBadRequest  %+v", 400, o.Payload)
}

func (o *GetEnabledPoliciesBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetEnabledPoliciesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEnabledPoliciesInternalServerError creates a GetEnabledPoliciesInternalServerError with default headers values
func NewGetEnabledPoliciesInternalServerError() *GetEnabledPoliciesInternalServerError {
	return &GetEnabledPoliciesInternalServerError{}
}

/*GetEnabledPoliciesInternalServerError handles this case with default header values.

Internal server error
*/
type GetEnabledPoliciesInternalServerError struct {
}

func (o *GetEnabledPoliciesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /enabled][%d] getEnabledPoliciesInternalServerError ", 500)
}

func (o *GetEnabledPoliciesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
