package gateway

/**
 * Panther is a scalable, powerful, cloud-native SIEM written in Golang/React.
 * Copyright (C) 2020 Panther Labs Inc
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import (
	"testing"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/service/cognitoidentity"
	"github.com/stretchr/testify/assert"
)

func TestValidateToken(t *testing.T) {
	mockFedIdentityClient := &MockFedIdentityClient{}
	mockFedIdentityClient.On("GetCredentialsForIdentity", &cognitoidentity.GetCredentialsForIdentityInput{
		IdentityId: aws.String("us-east-1:116cf59a-ef99-41c3-a3f8-b8651db1b5c7"),
		Logins: map[string]*string{
			"cognito-idp.us-west-2.amazonaws.com/us-west-2_8IbrUHXlp": aws.String("eyJraWQiOiJwN1wveVpHa3VibEJQcjhqY3ZcL2Z1NWRNRHlvQ21KWjh6VmQ2bU5XSnVSRFk9IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiI4NDljZWRmMi01NGIxLTQ4OWMtOGIzMy03Y2U1NzQ3MmRhN2EiLCJjb2duaXRvOmdyb3VwcyI6WyJBZG1pbnMiXSwiZW1haWxfdmVyaWZpZWQiOnRydWUsImN1c3RvbTpvcmdhbml6YXRpb25faWQiOiI2ZTMxMDczYi1iMWZjLTQ1NGEtOWUxMC0yN2ZlYjY3MzY0ZjYiLCJjb2duaXRvOnByZWZlcnJlZF9yb2xlIjoiYXJuOmF3czppYW06Ojg5MTUzMDU2MDE1Nzpyb2xlXC9JZGVudGl0eVBvb2xBdXRoZW50aWNhdGVkQWRtaW5zUm9sZSIsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy13ZXN0LTIuYW1hem9uYXdzLmNvbVwvdXMtd2VzdC0yXzhJYnJVSFhscCIsImNvZ25pdG86dXNlcm5hbWUiOiI4NDljZWRmMi01NGIxLTQ4OWMtOGIzMy03Y2U1NzQ3MmRhN2EiLCJnaXZlbl9uYW1lIjoiUXVhbiIsImNvZ25pdG86cm9sZXMiOlsiYXJuOmF3czppYW06Ojg5MTUzMDU2MDE1Nzpyb2xlXC9JZGVudGl0eVBvb2xBdXRoZW50aWNhdGVkQWRtaW5zUm9sZSJdLCJhdWQiOiIzcHRvaGh1dHAxOWdzYTRtaWtmYzhrNTZ2byIsImV2ZW50X2lkIjoiYjg3ODQzZjEtNTRiNS00NGZlLTkyZGEtM2NhZWVmNjc4YjEyIiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE1Njg2NTU1ODMsImV4cCI6MTU2ODY1OTE4NCwiaWF0IjoxNTY4NjU1NTg0LCJmYW1pbHlfbmFtZSI6IlBoYW0iLCJlbWFpbCI6InF1YW4ucGhhbUBydW5wYW50aGVyLmlvIn0.NyXb6-1R95JIzVZYP_yJL_zYyHhMbqKa_wGPn5uXOPaEAXZqeWjCnGHtpGhRwBl8kZnaXO2EJuWwkZ7bFQgbZL05wBIisd5pO3hRxIb5aHNfU4POQoNF6VrZawbNt3sWm8qZnSkJj_vQkm1MVEntbFqgL6l5MOqcdSRJ31RBAMZozhUgEFqwUoSjBpuq-_KbwYzfoXwxya-jJPUZyYEsgMbrflL_00Gxt9A0o86QlrEN0mTmg0ZFB2ZIhEoOXJ5xoHc9KU1PSoVcwYK3MtjsLS9i-XxXcjoICNf7i1Dq8zb72HfoluquIRsqbd8xRItQG3MJVF_NbQ8EN07Z5OWoMQ"), //nolint:lll
		},
	}).Return(&cognitoidentity.GetCredentialsForIdentityOutput{}, nil)
	gw := &UsersGateway{fedIdentityClient: mockFedIdentityClient}
	res, err := gw.ValidateToken(aws.String("us-east-1:116cf59a-ef99-41c3-a3f8-b8651db1b5c7"), aws.String("eyJraWQiOiJwN1wveVpHa3VibEJQcjhqY3ZcL2Z1NWRNRHlvQ21KWjh6VmQ2bU5XSnVSRFk9IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiI4NDljZWRmMi01NGIxLTQ4OWMtOGIzMy03Y2U1NzQ3MmRhN2EiLCJjb2duaXRvOmdyb3VwcyI6WyJBZG1pbnMiXSwiZW1haWxfdmVyaWZpZWQiOnRydWUsImN1c3RvbTpvcmdhbml6YXRpb25faWQiOiI2ZTMxMDczYi1iMWZjLTQ1NGEtOWUxMC0yN2ZlYjY3MzY0ZjYiLCJjb2duaXRvOnByZWZlcnJlZF9yb2xlIjoiYXJuOmF3czppYW06Ojg5MTUzMDU2MDE1Nzpyb2xlXC9JZGVudGl0eVBvb2xBdXRoZW50aWNhdGVkQWRtaW5zUm9sZSIsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy13ZXN0LTIuYW1hem9uYXdzLmNvbVwvdXMtd2VzdC0yXzhJYnJVSFhscCIsImNvZ25pdG86dXNlcm5hbWUiOiI4NDljZWRmMi01NGIxLTQ4OWMtOGIzMy03Y2U1NzQ3MmRhN2EiLCJnaXZlbl9uYW1lIjoiUXVhbiIsImNvZ25pdG86cm9sZXMiOlsiYXJuOmF3czppYW06Ojg5MTUzMDU2MDE1Nzpyb2xlXC9JZGVudGl0eVBvb2xBdXRoZW50aWNhdGVkQWRtaW5zUm9sZSJdLCJhdWQiOiIzcHRvaGh1dHAxOWdzYTRtaWtmYzhrNTZ2byIsImV2ZW50X2lkIjoiYjg3ODQzZjEtNTRiNS00NGZlLTkyZGEtM2NhZWVmNjc4YjEyIiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE1Njg2NTU1ODMsImV4cCI6MTU2ODY1OTE4NCwiaWF0IjoxNTY4NjU1NTg0LCJmYW1pbHlfbmFtZSI6IlBoYW0iLCJlbWFpbCI6InF1YW4ucGhhbUBydW5wYW50aGVyLmlvIn0.NyXb6-1R95JIzVZYP_yJL_zYyHhMbqKa_wGPn5uXOPaEAXZqeWjCnGHtpGhRwBl8kZnaXO2EJuWwkZ7bFQgbZL05wBIisd5pO3hRxIb5aHNfU4POQoNF6VrZawbNt3sWm8qZnSkJj_vQkm1MVEntbFqgL6l5MOqcdSRJ31RBAMZozhUgEFqwUoSjBpuq-_KbwYzfoXwxya-jJPUZyYEsgMbrflL_00Gxt9A0o86QlrEN0mTmg0ZFB2ZIhEoOXJ5xoHc9KU1PSoVcwYK3MtjsLS9i-XxXcjoICNf7i1Dq8zb72HfoluquIRsqbd8xRItQG3MJVF_NbQ8EN07Z5OWoMQ")) //nolint:lll
	assert.NoError(t, err)
	assert.NotNil(t, res)
}
