# Copyright 2020 Panther Labs Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

AWSTemplateFormatVersion: 2010-09-09
Description: Prerequisite S3 buckets which must exist before the Panther stack can be deployed

Parameters:
  AccessLogsBucketName:
    Type: String
    Description: Optional bucket for storing S3 access logs. If not specified, one is created for you
    Default: ''

Conditions:
  CreateLogBucket: !Equals [!Ref AccessLogsBucketName, '']

Resources:
  # S3 bucket for Panther S3 access logs
  AccessLogsBucket:
    Condition: CreateLogBucket
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub panther-s3-logs-${AWS::AccountId}-${AWS::Region}
      LifecycleConfiguration:
        Rules:
          # Keep access logs for 1 year, permanently delete 30 days after they expire
          - ExpirationInDays: 365
            NoncurrentVersionExpirationInDays: 30
            Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Sub panther-s3-logs-${AWS::AccountId}-${AWS::Region}
        LogFilePrefix: !Sub panther-s3-logs-${AWS::AccountId}-${AWS::Region}/
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  # S3 bucket for CloudFormation to upload templates, Lambda source, etc
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub panther-source-${AWS::AccountId}-${AWS::Region}
      LifecycleConfiguration:
        Rules:
          # Once a stack is deployed, its resources in S3 can be safely removed.
          - ExpirationInDays: 90
            Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !If [CreateLogBucket, !Ref AccessLogsBucket, !Ref AccessLogsBucketName]
        LogFilePrefix: !Sub panther-source-${AWS::AccountId}-${AWS::Region}/
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

Outputs:
  LogBucketName:
    Description: S3 bucket name for Panther S3 access logs
    Value: !If [CreateLogBucket, !Ref AccessLogsBucket, !Ref AccessLogsBucketName]
    Export:
      Name: Panther-LogBucket
  SourceBucketName:
    Description: S3 bucket name for Panther CloudFormation packaging
    Value: !Ref SourceBucket
    Export:
      Name: Panther-SourceBucket
